name: Deploy via SSH

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent with the private key
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KEY }}  

      # Step 3: Deploy quietly via SSH
      - name: Deploy via SSH
        run: |
          export SSH_ASKPASS=/bin/true
          setsid ssh -q -o StrictHostKeyChecking=no -o LogLevel=ERROR -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd robots
            git pull origin master > /dev/null 2>&1
            sh robots_publish.sh > /dev/null 2>&1
          EOF
