name: Deploy via SSH

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent with the private key
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KEY }}  

      # Step 3: SSH into the server and execute commands quietly
      - name: Deploy via SSH
        run: |
          script -q -c "ssh -q -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd robots
            git pull origin master 
            sh robots_publish.sh 
          EOF" /dev/null
