name: Deploy via SSH

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent with the private key
      - name: Set up SSH Agent
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KEY }}  

      # Step 3: SSH into the server and execute commands
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no be@login.robots.ox.ac.uk << 'EOF'
            cd /robots
            git pull origin master
            ./robots.sh  # Replace with your script
          EOF

